sudo: required
language: python
python:
  - "3.7"
services:
  - docker
install: "pip install -r requirements.txt"
script:
  - coverage run unittest_api.py
  - docker build -t filipegorodscy/a2 .
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker logout
  - docker login -u filipegorodscy
  #- echo "Q\!w2e3r4t5" | docker login -u "filipegorodscy" --password-stdin
  - docker push filipegorodscy/a2
##kgk
#sudo: required
#language: python
#services:
#- docker
#
#install: "pip install -r requirement.txt"
#
#script:
##- coverage run unittest_api.py
#- docker image build -t zaidalica/cps847-group6-assignment2 .
#
#after_success:
#  #- bash <(curl -s https://codecov.io/bash)
#  #log in to docker CLI
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#  #take built images and push to DOcker hub
#  - docker push zaidalica/cps847-group6-assignment2
#  #test
#
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "test"
#  env: "Test-env"
#  bucket_name: "elasticbeanstalk-us-east-2-238413349601"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
